config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :comments, only: [:edit, :destroy, :update, :create]

resources :blog_posts

get '/:name' => 'blog_posts#user_posts', as: :user_posts

root 'blog_posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

	has_many :comment, dependent: :destroy
	belongs_to :user
	

	validates :title, :blog_entry, presence: true
	validates :title, length: { maximum: 140 }

	paginates_per 3
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :blog_post
	belongs_to :user

	validates :comment_entry, :blog_post_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :blog_posts, dependent: :destroy
   has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :configure_premitted_parameters, if: :devise_controller?

  protected

  def configure_premitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
  	devise_parameter_sanitizer.permit(:account_update, keys:[:username])
end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

	before_action :set_blog_post, only: [:show, :edit, :destroy, :update]
  include ApplicationHelper
	
  def index
  	@blog_posts = BlogPost.order(created_at: :desc).page(params[:page])
  end

  def show
    @comment = Comment.new
  end


  def edit
    no_access_visitors(current_user, @blog_post)
      end

  def new
  	@blog_post = BlogPost.new
  end

def user_posts
  @user = User.find_by(username: params[:name])
end

  def create
  	@blog_post = BlogPost.new(blog_post_params)

  	respond_to do |format|
  		if @blog_post.save
  			format.html { redirect_to blog_post_url(@blog_post), notice: "Blog Post was created successfully"}
  		else
  			format.html { render :new }
  		end  		
  	end
end

def update
	respond_to do |format|
  		if @blog_post.update(blog_post_params)
  			format.html { redirect_to blog_post_url(@blog_post), notice: "Blog Post was updated successfully"}
  		else
  			format.html { render :edit }
  		end  		
  	end	
end

def destroy
	@blog_post.destroy

	respond_to do |format|
  		  			format.html { redirect_to blog_posts_url, notice: "Blog Post was DESTROYEEEEDDD!!!!"}
  		end	
end

private

def set_blog_post
	@blog_post = BlogPost.find(params[:id])
end

def blog_post_params
	params.require(:blog_post).permit(:title, :blog_entry, :user_id)
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :set_comment, only: [:edit, :update, :destroy]
	
  def edit
    @blog_post = BlogPost.find(@comment.blog_post_id)
    no_access-visitors(current_user, @comment)
  end

  def create
  	@comment = Comment.new(comment_params)

  	respond_to do |format|
  		if @comment.save
  			format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment was created successfully!"}

  		else
  			format.html { redirect_to :back, notice: "comment failed to post"}
  		end  		
  	end
end

	def update
		respond_to do |format|
			if @comment.update(comment_params)
  			format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Comment was updated successfully!"}

  		else
  			format.html { render :edit}
  		end  		
  	end			
end

	def destroy
    @comment.destroy
		respond_to do |format|
			format.html { redirect_to blog_post_url(id: @comment.blog_post_id), notice: "Your comment was destroyed!!!!"}

  		end  		
  	end			


private

	def comment_params
	params.require(:comment).permit(:user_id, :comment_entry, :blog_post_id)	
end
	def set_comment
		@comment = Comment.find(params[:id])
		
	end
 end

app/helpers/application_helper.rb
module ApplicationHelper

def no_access_visitors(current_user, post_user)
    unless current_user.id == post_user.user_id
    redirect_to root_url
  end
end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>


	<% if @blog_post.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post form being saved:</h2>

		<ul>
			<% @blog_post.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<%end%>
			</ul>
	</div>
		<% end %>
			<div class="form-group">
				<%= form.text_field :title, class: "form-control", placeholder: "Blog Title..." %>				
			</div>

			<div class="form-group hidden">
				<%= form.number_field :user_id, value: current_user.id  %>				
			</div>
			<div class="form-group">
				<%= form.text_area :blog_entry, class: "form-control", rows: 12, placeholder: "Tell Us Something..." %>				
			</div>

			<div class="actions">
				<%= form.submit "Post", class: "btn btn-primary" %>
			</div>

<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post/h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@blog_post), class: "btn btn-info" %>

<%= link_to "All Blog posts", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/index.html.erb
<h1>Welcome <%= current_user.username %></h1>
<div class="row">
	<% @blog_posts.each do |blog_post| %>
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<%= link_to blog_post.title, blog_post %>
			</div>

				<div class="panel-body">
					by <%= link_to blog_post.user.username, user_posts_path(name: blog_post.user.username) %><br>
					<p><i>Created: <%= blog_post.created_at.strftime("%m/%d/Y%Y at %I:%M%P") %></i></p>
					<p><%= blog_post.blog_entry[0..150].html_safe %>....<%= link_to 'read more', blog_post %></p> 
				</div>
				<div class="panel-footer">
					<% if blog_post.user_id == current_user.id %>				
					<%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %>
					<%= link_to "Destroy", blog_post, method: :delete, data: { confirm: "Are you Sure?" }, class: "btn btn-danger" %>
					<% end %>
				</div>
			</div>	
		</div>
	<% end %>
</div>

<%= paginate @blog_posts %>
	

app/views/blog_posts/new.html.erb
<h1>Create a New Blog post</h1>

<%= render 'form' %>

<br>

<% link_to "All Blog Post", blog_posts_path, class: "btn btn-default" %>

app/views/blog_posts/show.html.erb
<div class= "panel panel-primary">
	<div class="panel-heading">
		<%= @blog_post.title %>
	</div>
	<div class="panel-body">
		<p> by <%= @blog_post.user.username %></p>
		<p><%= time_ago_in_words(@blog_post.created_at) %> age</p>
		<p><%= @blog_post.blog_entry.html_safe %></p>

	</div>
	<div class="panel-footer">
		<% if @blog_post.user_id == current_user.id %>	
		<%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn-warning" %>
		<% end %>
		<%= link_to "All Blog Posts", blog_posts_path,  class: "btn btn-default" %>

	</div>

</div>

<div class="panel panel-success">
	<div class= panel-heading>
		Make a comment....		
	</div>
	<div class="panel-body">
		<%= render 'comments/form' %>		
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		All Comments...		
	</div>

	<div class="panel-body">
		<%= render @comment %>
		
	</div>

</div>

app/views/blog_posts/user_posts.html.erb
<h1>All Post by <b><%= @user.username %></b></h1>

<% @user.blog_posts.each do |blog_post| %>


	<div class="row">
		<div class="col-md-12">
			<div class="well">
				<h3><%= link_to blog_post.title, blog_post %></h3>
				<p><em>posted on <%= blog_post.created_at.strftime("%m/%d/%Y at %I:%M%P") %></em></p>	
				<p>
					<%= blog_post.blog_entry.html_safe %>
				</p>
				<p>
					<% if current_user.id == blog_post.user_id %>
					<%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn_warning" %>
					<%= link_to "Destroy", blog_post, method: :delete, data: { confirm: "Are you Sure?" }, class: "btn btn-danger" %>
					<% end %>					
				</p>
			</div>			
		</div>		
	</div>
<% end %>

app/views/comments/_comment.html.erb
<% @blog_post.comment.each do |comment| %>
	
	<h4><%= link_to comment.user.username, user_posts_path(name: comment.user.username) %></h4>
	<h4><%= time_ago_in_words(comment.created_at) %> ago</h4>
	<p><%= comment.comment_entry %></p>
	<% if current_user.id == comment.user.id%>
	<%= link_to "Edit", edit_comment_path(comment), class: "btn btn-warning" %>
	<%= link_to "Destroy", comment, method: :delete, data: {confirm: "Are you Sure?"}, class: "btn btn-dnager"%>
	<% end %>


<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>


	<% if @comment.errors.any? %>
	<div class="error_explanation">
		<h2><%= pluralize(@comment.errors.count, "error") %> prohibited this blog post for being saved:</h2>
		
		<ul>
			<% @comment.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="form-group hidden">
	<%= form.number_field :user_id, value: current_user.id  %>	
</div>

<div class="form-group">
	<%= form.text_area :comment_entry, rows: 4, class: "form-control", placeholder: "Enter Comment Here...." %>	
</div>

<div class="form-group hidden">
	<%= form.number_field :blog_post_id, value: @blog_post.id %>	
</div>
<div class="actions">
	<%= form.submit "Set Comment", class: "btn btn-default" %>
	
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comments</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@comment.blog_post_id), class: "btn btn-info" %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <ul class="nav navbar-nav navbar-left">
          	<li><%= link_to "All Blog Posts", root_path, class: "navbar-brand" %></li>
          	<li><%= link_to "New Blog Post", new_blog_post_path %></li>
          </ul>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= gravatar_tag current_user.email, size: 20 %> <%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
              
            </ul>
          </li>
          

        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= render 'layouts/navbar' %>

  <div class="container">
  	<%= yield %>
  </div>


 
  </body>
</html>